### ISSUE TITLE
The color of the BACK button after a finished daily word

### ISSUE THREAD

**Issue by khlsvr** [La-Lojban/valsr#9]
After having finished a daily word, the fastest access to continue playing is pressing the BACK button which takes you now to the chain game. Maybe change this button's text to CHAIN GAME, CHAIN or such and change its color to blue, red or something similarly noticable so people less familiar with the UI know the fastest way to continue playing

**Comment by lagleki** [comment]
fixed in https://github.com/La-Lojban/valsr/commit/d781d05b1beeebf255495712c04164a9300fbd04
